on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["8.1", "8.2", "stable", "current"]
        racket-variant: ["BC", "CS"]
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.6
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing packages and their dependencies
        run: raco pkg install --no-docs --auto --link smalltalk-reader smalltalk-parser
      - name: Compiling smalltalk-reader and its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps --pkgs smalltalk-reader
      - name: Compiling smalltalk-parser and its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps --pkgs smalltalk-parser
      - name: Testing packages
        run: raco test -xt -p smalltalk-reader smalltalk-parser
