on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (CS)"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["8.18", "8.17", "pre-release", "stable", "current"]
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.14
        with:
          architecture: x64
          distribution: full
          variant: "CS"
          version: ${{ matrix.racket-version }}
      - name: Installing packages and their dependencies
        run: raco pkg install --no-docs --auto --link smalltalk-reader
      - name: Compiling smalltalk-reader and its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps --pkgs smalltalk-reader
      - name: Testing packages
        run: raco test -xt -p smalltalk-reader
